/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2024-09-04 11:42:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class huinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/test2/footer.jsp", Long.valueOf(1725448213485L));
    _jspx_dependants.put("/test2/header.jsp", Long.valueOf(1725448213496L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tsection {\r\n");
      out.write("\t\tmargin-bottom: 10%;\r\n");
      out.write("\t}\r\n");
      out.write("\th2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable {\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable, tr,td {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction onsub() {\r\n");
      out.write("\t\tconst elementNo = document.getElementById(\"no\");\r\n");
      out.write("\t\tconst elementName = document.getElementById(\"name\");\r\n");
      out.write("\t\tconst elementCode = document.getElementById(\"code\");\r\n");
      out.write("\t\tconst elementSchool = document.getElementById(\"school\");\r\n");
      out.write("\t\tconst elementJumin1 = document.getElementById(\"jumin1\");\r\n");
      out.write("\t\tconst elementJumin2 = document.getElementById(\"jumin2\");\r\n");
      out.write("\t\tconst elementMajor = document.getElementById(\"major\");\r\n");
      out.write("\t\tconst regExp = /[0-9]/; // 숫자인 경우\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(elementNo.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementName.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementCode.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementSchool.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementJumin1.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementJumin2.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(elementMajor.value.length == \"0\"){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(regExp.test()){\r\n");
      out.write("\t\t\talert(\"후보 번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("\t\t\telementNo.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\theader {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding: 5px;\r\n");
      out.write("\t\tbackground-color: gray; \r\n");
      out.write("\t}\r\n");
      out.write("\tnav {\r\n");
      out.write("\tbackground-color: skyblue; \r\n");
      out.write("\t}\r\n");
      out.write("\ta {\r\n");
      out.write("\tmargin-left: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<h2>(과정평가형 정보처리 산업기사 ) 학생회장 투표프로그램 ver 2021-10</h2>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<a href=\"husearch.jsp\">후보조회</a>\r\n");
      out.write("\t\t<a href=\"huinsert.jsp\">후보등록</a>\r\n");
      out.write("\t\t<a href=\"votego.jsp\">투표하기</a>\r\n");
      out.write("\t\t<a href=\"voteresult.jsp\">투표결과조회</a>\r\n");
      out.write("\t\t<a href=\"voterank.jsp\">후보자순위</a>\r\n");
      out.write("\t\t<a href=\"index.jsp\">홈으로</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<h2>후보등록</h2>\r\n");
      out.write("\t\t<form name=\"frm\" method=\"get\" action=\"action.jsp\">\r\n");
      out.write("\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>후보번호</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"no\" id=\"no\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"name\" id=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>팀번호</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"code\" id=\"code\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P1s\">1팀</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P2\">2팀</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P3\">3팀</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P4\">4팀</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P5\">5팀</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"P6\">6팀</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>학력</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"school\" id=\"school\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">==학력을 선택하세요==</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">중졸</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">고졸</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">전문대졸</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">대졸</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">석사수료</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"6\">석사취득</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"7\">박사수료</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"8\">박사취득</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주민번호</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"jumin1\" id=\"jumin1\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"jumin2\" id=\"jumin2\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>전공학년반</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"major\" id=\"major\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"등록\" onclick=\"return onsub()\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\tfooter{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<strong>\r\n");
      out.write("\t\t\tHRDKOREA Copyright 2021 All right reserved.\r\n");
      out.write("\t\t</strong>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
